version: '3.8'

services:
  kafka:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  postgres:
    image: postgres:latest
    container_name: userdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data

  mongodb:
    container_name: logdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    depends_on:
      - zipkin

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
#    container_name: invoicedb
#    environment:
#      - transport.host=localhost
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      esnet:
#    depends_on:
#      - zipkin

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    networks:
      - monitor-net
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  kafka_data:
  mongodb_data:
  esdata1:
  grafana-data:
  grafana-config:
networks:
  esnet:
  monitor-net: